### PR TITLE
Fix readme.me

### PR DESCRIPTION
**Pull request by jamesproud**
Changed deprecated command and fixed file location.

### CODE REVIEW

**Comment by eshvk** [comment]
👍

**Comment by eshvk** [comment]
@jamesproud Is there a reason you went with `gcloud compute copy-files` rather than `gcloud compute scp` ? Looking at the GCP API, looks like the former is deprecated?  See [here](https://cloud.google.com/sdk/gcloud/reference/compute/copy-files)

**Comment by jamesproud** [comment]
@eshvk my changes were to change from `copy-files` to `scp`, not vice versa.

screen shot 2017-08-30 at 14 41 57

**Comment by eshvk** [comment]
Ah sorry, my mistake, it's been a while since I looked at the code. Thanks and merging!

**Pull request merged**
